### ISSUE TITLE
uninitialized constant ActiveScaffold

### ISSUE THREAD

**Issue by duderonomy** [activescaffold/active_scaffold#595] opened 2018-05-27 20:04 UTC
In a new Rails 5 project, followed instructions "Commands for Rails 5". 

My routes.rb file:
```
Rails.application.routes.draw do
  concern :active_scaffold_association, ActiveScaffold::Routing::Association.new
  concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
  resources :blogs, concerns: :active_scaffold
  resources :users, concerns: :active_scaffold
  resources :blog
end
```

Browser output on page:
http://0.0.0.0:3000/blog
```
NameError
uninitialized constant ActiveScaffold
Extracted source (around line #2):            
1 Rails.application.routes.draw do
2   concern :active_scaffold_association, ActiveScaffold::Routing::Association.new
3   concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
4  resources :blogs, concerns: :active_scaffold
5  resources :users, concerns: :active_scaffold
```

There may not be any issue. I do not know. I am not experienced enough to know essential Rails knowledge. It is possible there is more to do which an experienced Rails programmer would know. 

Thank you for the active_scaffold gem.

**Comment by scambra** [comment] 2018-05-28 08:03
What rails 5 version? What is activescaffold version in Gemfile.lock?

**Comment by duderonomy** [comment] 2018-05-29 00:15
Rails 5.1.5
    active_scaffold (3.5.1)

Thank you! 
At conclusion, I hope this proves to useful for you. 
Pls let me know what more I can do.

**Comment by duderonomy** [comment] 2018-05-29 21:04
Forgive me for not providing:
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]`

**Comment by scambra** [comment] 2018-05-30 11:55
I can't reproduce, tried with ruby 2.3 and 2.4.2, same rails and activescaffold versions. Loading controller and rails routes work.

**Comment by gregschmit** [comment] 2022-10-25 22:02
Closing as not reproducible.

@duderonomy if you can show a minimal, complete, and verifiable example (e.g., reproduce the issue in a repo and link to it here), then we can re-open this.

**Closed by gregschmit** 2022-10-25 22:02 UTC
